grammar basic = [
  syntax main = p*;
  syntax p = a | b;
  syntax a = 'program';
  syntax b = 'hello';
]

match(main)
{
  | => { 
        print ("\nmain");
        $0.value;
	
  }
}

match(p)
{
  | 0 => {
        print("\np0");
        $0.value;
  }
  | 1 => {
        print("\np1");
        $0.value;
  }
}

match (a) 
{
  | => { print ("\na 0"); }
}

match (b) 
{
  | => { print ("\nb 0"); }
}


print("\nhello " .. "world");

program hello