grammar oo = [
  syntax main = s*;
  syntax s = i_class ';' | i_expr ';' ;
  syntax i_class = 'class' i_id '{' i_field* '}' ;
  syntax i_id = "[a-zA-z][a-zA-z0-9_]*";
  syntax i_digit = "[0-9][0-9]*";
  syntax i_syntax_id = 'int' | 'float';
  syntax i_field = i_syntax_id i_id ';';
  syntax i_expr = i_expr '=' i_expr  
            | i_expr '.' i_expr
            | i_literal;
  syntax i_literal = i_id | i_digit;
  
]

class x {};

class test {
  int x;
};

x = 0;
test.x = 1;