grammar basic = [
  syntax main = p*;
  syntax p = a | b;
  syntax a = 'program';
  syntax b = 'hello';
]

match(main)
{
  | => { 
        print ("main");
        $0.value;
	
  }
}

match(p)
{
  | 0 => {
        print("p0");
        $0.value;
  }
  | 1 => {
        print("p1");
        $0.value;
  }
}

match (a) 
{
  | => { print ("a 0"); }
}

match (b) 
{
  | => { print ("b 0"); }
}


print("hello");

program hello